---
openstack_api_versions:
  \"identity\": 3

os_env:
  OS_AUTH_TYPE: v3password
  OS_AUTH_URL: https://{{ ansible_fqdn }}:5000/v3
  OS_USERNAME: admin
  OS_PASSWORD: password
  OS_PROJECT_NAME: admin
  OS_USER_DOMAIN_ID: default
  OS_PROJECT_DOMAIN_ID: default
  OS_IDENTITY_API_VERSION: 3

os_env_v2:
  OS_AUTH_TYPE: v3password
  OS_AUTH_URL: https://{{ ansible_fqdn }}:5000/v3
  OS_USERNAME: admin
  OS_PASSWORD: password
  OS_PROJECT_NAME: admin
  OS_USER_DOMAIN_ID: default
  OS_PROJECT_DOMAIN_ID: default
  OS_IDENTITY_API_VERSION: 2
  OS_TENANT_NAME: admin

service_authtoken:
  auth_uri: "https://{{ hostname }}:5000"
  auth_plugin: v3fedkerb
  auth_url: "https://{{ hostname }}:5000/v3"
  identity_provider: sssd
  protocol: kerberos
  project_name: services
  project_domain_id: default

mysql_principal: MySQL/{{ ansible_fqdn  }}@{{ ipa_realm }}

glance_api_haproxy_port: 9293
cinder_api_haproxy_port: 8777
neutron_api_haproxy_port: 9697
nova_api_haproxy_port: 8778
nova_ec2_haproxy_port: 8779
barbican_haproxy_port: 9313


#Messaging options



oslo_messaging_ampq:
  allow_insecure_clients: True
  broadcast_prefix: broadcast
  group_request_prefix: unicast
  idle_timeout: 0
  server_request_prefix: exclusive
  trace: False
  sasl_mechanisms: GSSAPI

# Set of options to remove: these are 
# setup by packstack in the default section of the
# services config files
default_messaging_options:
          - qpid_hostname
          - qpid_username
          - qpid_password
          - qpid_heartbeat
          - qpid_protocol
          - qpid_tcp_nodelay
          - qpid_port
          - rpc_backend

rabbit_messaging_options:
        - rabbit_host
        - rabbit_port
        - rabbit_hosts
        - rabbit_use_ssl
        - rabbit_userid
        - rabbit_password
        - rabbit_virtual_host
        - rabbit_ha_queues
        - heartbeat_timeout_threshold
        - heartbeat_rate


ampq_conf_options:
  topic-patterns: broadcast
  queue-patterns: unicast
  queue-patterns: exclusive

amqp_transport_url: amqp://{{ ansible_fqdn }}

my_cnf:
  datadir: /var/lib/mysql
  socket: /var/lib/mysql/mysql.sock
  log-error: /var/log/mariadb/mariadb.log
  pid-file: /var/run/mariadb/mariadb.pid

nova_cinder_endpoint: https://{{ hostname }}:8776/vfoo1/%%(project_id)s
